# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'radioButton.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(468, 465)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lblUlke = QtWidgets.QLabel(self.centralwidget)
        self.lblUlke.setGeometry(QtCore.QRect(10, 330, 201, 41))
        self.lblUlke.setObjectName("lblUlke")
        self.lblEgitim = QtWidgets.QLabel(self.centralwidget)
        self.lblEgitim.setGeometry(QtCore.QRect(240, 330, 211, 41))
        self.lblEgitim.setText("")
        self.lblEgitim.setObjectName("lblEgitim")
        self.btn_SelectedCt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_SelectedCt.setGeometry(QtCore.QRect(10, 260, 201, 51))
        self.btn_SelectedCt.setObjectName("btn_SelectedCt")
        self.btn_SelectedEdu = QtWidgets.QPushButton(self.centralwidget)
        self.btn_SelectedEdu.setGeometry(QtCore.QRect(240, 260, 211, 51))
        self.btn_SelectedEdu.setObjectName("btn_SelectedEdu")
        self.groupBoxCountry = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxCountry.setGeometry(QtCore.QRect(10, 20, 201, 221))
        self.groupBoxCountry.setObjectName("groupBoxCountry")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBoxCountry)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 161, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayoutCountry = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayoutCountry.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutCountry.setObjectName("gridLayoutCountry")
        self.btn_fr = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.btn_fr.setObjectName("btn_fr")
        self.gridLayoutCountry.addWidget(self.btn_fr, 2, 0, 1, 1)
        self.btn_tr = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.btn_tr.setObjectName("btn_tr")
        self.gridLayoutCountry.addWidget(self.btn_tr, 0, 0, 1, 1)
        self.btn_de = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.btn_de.setObjectName("btn_de")
        self.gridLayoutCountry.addWidget(self.btn_de, 1, 0, 1, 1)
        self.btn_ge = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.btn_ge.setObjectName("btn_ge")
        self.gridLayoutCountry.addWidget(self.btn_ge, 3, 0, 1, 1)
        self.groupBoxEdu = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxEdu.setGeometry(QtCore.QRect(240, 20, 211, 221))
        self.groupBoxEdu.setObjectName("groupBoxEdu")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBoxEdu)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 171, 151))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayoutEdu = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayoutEdu.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutEdu.setObjectName("gridLayoutEdu")
        self.edu_hgh = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.edu_hgh.setObjectName("edu_hgh")
        self.gridLayoutEdu.addWidget(self.edu_hgh, 2, 0, 1, 1)
        self.edu_pri = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.edu_pri.setObjectName("edu_pri")
        self.gridLayoutEdu.addWidget(self.edu_pri, 0, 0, 1, 1)
        self.edu_middle = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.edu_middle.setObjectName("edu_middle")
        self.gridLayoutEdu.addWidget(self.edu_middle, 1, 0, 1, 1)
        self.edu_col = QtWidgets.QRadioButton(self.gridLayoutWidget_2)
        self.edu_col.setObjectName("edu_col")
        self.gridLayoutEdu.addWidget(self.edu_col, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 468, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblUlke.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btn_SelectedCt.setText(_translate("MainWindow", "Ülke Seçimi"))
        self.btn_SelectedEdu.setText(_translate("MainWindow", "Eğitim Seçimi"))
        self.groupBoxCountry.setTitle(_translate("MainWindow", "Country"))
        self.btn_fr.setText(_translate("MainWindow", "FRANCE"))
        self.btn_tr.setText(_translate("MainWindow", "TURKEY"))
        self.btn_de.setText(_translate("MainWindow", "GERMANY"))
        self.btn_ge.setText(_translate("MainWindow", "GREECE"))
        self.groupBoxEdu.setTitle(_translate("MainWindow", "Education Level"))
        self.edu_hgh.setText(_translate("MainWindow", "HIGH SCHOOL"))
        self.edu_pri.setText(_translate("MainWindow", "PRIMARY SCHOOL"))
        self.edu_middle.setText(_translate("MainWindow", "MIDDLE SCHOOL"))
        self.edu_col.setText(_translate("MainWindow", "COLLAGE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
